services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:8080"
    #  - "7234:443"
    environment:
      # - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=product_database;Username=username;Password=strong_password
    
    # Att denna ska starta efter databas-containern startats
    depends_on:
      - database
    container_name: webapp

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: strong_password
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: db

volumes:
  postgres-data:
